[package]
name = "infrastructure"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
dashmap = { workspace = true }
arc-swap = { workspace = true }
parking_lot = { workspace = true }
crossbeam-utils = "0.8"  # For CachePadded as recommended by Sophia

[dev-dependencies]
criterion = { workspace = true }
proptest = { workspace = true }

# Loom for concurrency testing
[target.'cfg(loom)'.dependencies]
loom = "0.7"