#!/bin/bash
# MCP Wrapper for exchangespec
# Auto-generated by setup-mcp-agents.sh

# Ensure container is running
if ! docker ps --filter "name=mcp-exchangespec" --format "{{.Names}}" | grep -q "mcp-exchangespec"; then
    echo "Starting mcp-exchangespec container..." >&2
    docker-compose -f "/home/hamster/bot4/mcp/docker-compose-agents.yml" up -d exchangespec >&2
    sleep 3
fi

# Forward stdio to Docker container
exec docker exec -i mcp-exchangespec /app/exchangespec
