#!/bin/bash
# MCP Wrapper for architect
# Auto-generated by setup-mcp-agents.sh

# Ensure container is running
if ! docker ps --filter "name=mcp-architect" --format "{{.Names}}" | grep -q "mcp-architect"; then
    echo "Starting mcp-architect container..." >&2
    docker-compose -f "/home/hamster/bot4/mcp/docker-compose-agents.yml" up -d architect >&2
    sleep 3
fi

# Forward stdio to Docker container
exec docker exec -i mcp-architect /app/architect
