#!/bin/bash
# MCP Wrapper for qualitygate
# Auto-generated by setup-mcp-agents.sh

# Ensure container is running
if ! docker ps --filter "name=mcp-qualitygate" --format "{{.Names}}" | grep -q "mcp-qualitygate"; then
    echo "Starting mcp-qualitygate container..." >&2
    docker-compose -f "/home/hamster/bot4/mcp/docker-compose-agents.yml" up -d qualitygate >&2
    sleep 3
fi

# Forward stdio to Docker container
exec docker exec -i mcp-qualitygate /app/qualitygate
