#!/bin/bash
# MCP Wrapper for mlengineer
# Auto-generated by setup-mcp-agents.sh

# Ensure container is running
if ! docker ps --filter "name=mcp-mlengineer" --format "{{.Names}}" | grep -q "mcp-mlengineer"; then
    echo "Starting mcp-mlengineer container..." >&2
    docker-compose -f "/home/hamster/bot4/mcp/docker-compose-agents.yml" up -d mlengineer >&2
    sleep 3
fi

# Forward stdio to Docker container
exec docker exec -i mcp-mlengineer /app/mlengineer
