#!/bin/bash
# MCP Wrapper for integrationvalidator
# Auto-generated by setup-mcp-agents.sh

# Ensure container is running
if ! docker ps --filter "name=mcp-integrationvalidator" --format "{{.Names}}" | grep -q "mcp-integrationvalidator"; then
    echo "Starting mcp-integrationvalidator container..." >&2
    docker-compose -f "/home/hamster/bot4/mcp/docker-compose-agents.yml" up -d integrationvalidator >&2
    sleep 3
fi

# Forward stdio to Docker container
exec docker exec -i mcp-integrationvalidator /app/integrationvalidator
