#!/bin/bash
# MCP Wrapper for infraengineer
# Auto-generated by setup-mcp-agents.sh

# Ensure container is running
if ! docker ps --filter "name=mcp-infraengineer" --format "{{.Names}}" | grep -q "mcp-infraengineer"; then
    echo "Starting mcp-infraengineer container..." >&2
    docker-compose -f "/home/hamster/bot4/mcp/docker-compose-agents.yml" up -d infraengineer >&2
    sleep 3
fi

# Forward stdio to Docker container
exec docker exec -i mcp-infraengineer /app/infraengineer
