#!/bin/bash
# MCP Wrapper for riskquant
# Auto-generated by setup-mcp-agents.sh

# Ensure container is running
if ! docker ps --filter "name=mcp-riskquant" --format "{{.Names}}" | grep -q "mcp-riskquant"; then
    echo "Starting mcp-riskquant container..." >&2
    docker-compose -f "/home/hamster/bot4/mcp/docker-compose-agents.yml" up -d riskquant >&2
    sleep 3
fi

# Forward stdio to Docker container
exec docker exec -i mcp-riskquant /app/riskquant
