#!/bin/bash
# MCP Wrapper for coordinator
# Auto-generated by setup-mcp-agents.sh

# Ensure container is running
if ! docker ps --filter "name=mcp-coordinator" --format "{{.Names}}" | grep -q "mcp-coordinator"; then
    echo "Starting mcp-coordinator container..." >&2
    docker-compose -f "/home/hamster/bot4/mcp/docker-compose-agents.yml" up -d coordinator >&2
    sleep 3
fi

# Forward stdio to Docker container
exec docker exec -i mcp-coordinator /app/coordinator
