#!/bin/bash
# MCP Wrapper for complianceauditor
# Auto-generated by setup-mcp-agents.sh

# Ensure container is running
if ! docker ps --filter "name=mcp-complianceauditor" --format "{{.Names}}" | grep -q "mcp-complianceauditor"; then
    echo "Starting mcp-complianceauditor container..." >&2
    docker-compose -f "/home/hamster/bot4/mcp/docker-compose-agents.yml" up -d complianceauditor >&2
    sleep 3
fi

# Forward stdio to Docker container
exec docker exec -i mcp-complianceauditor /app/complianceauditor
