global:
  scrape_interval: 10s
  evaluation_interval: 10s
  
scrape_configs:
  - job_name: 'bot4-trading'
    static_configs:
      - targets:
        - 'trading-engine-1:9090'
        - 'trading-engine-2:9090'
        - 'trading-engine-3:9090'
        labels:
          environment: 'staging'
          
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        
  - job_name: 'timescaledb'
    static_configs:
      - targets: ['timescaledb:5432']
        
  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy:8080']

# Alert rules
rule_files:
  - '/etc/prometheus/alerts.yml'
  
# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
      - targets: []