apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bot4-trading

bases:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml
- hpa-patch.yaml

configMapGenerator:
- name: trading-config
  behavior: merge
  files:
  - config.toml=production-config.toml

secretGenerator:
- name: exchange-credentials
  behavior: replace
  envs:
  - production-secrets.env

replicas:
- name: bot4-trading-engine
  count: 5

images:
- name: bot4/trading-engine
  newTag: v0.3.0-prod
- name: bot4/config-validator
  newTag: v0.3.0-prod
- name: bot4/monitoring-sidecar
  newTag: v0.3.0-prod

commonAnnotations:
  environment: production
  deployment-date: "2025-08-29"
  
resources:
- external-secrets.yaml