# Production Overlay
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bot4-trading

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - hpa-patch.yaml

configMapGenerator:
  - name: bot4-config
    behavior: merge
    literals:
      - environment=production
      - log_level=info
      - monitoring_enabled=true

secretGenerator:
  - name: bot4-secrets
    behavior: replace
    envs:
      - secrets.env

replicas:
  - name: bot4-trading-engine
    count: 10

images:
  - name: bot4/trading-engine
    newTag: v1.0.0-prod
  - name: bot4/config-validator
    newTag: v1.0.0-prod

patches:
  - target:
      kind: Deployment
      name: bot4-trading-engine
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 16Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 8
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          node-type: trading-dedicated
          instance-type: c5n.4xlarge
