# Kubernetes Secrets for Bot4 Trading Platform
# Task 0.5.1 - Production Deployment Configuration
# WARNING: This is a TEMPLATE - DO NOT commit with real values!
# Use sealed-secrets or external-secrets-operator in production

apiVersion: v1
kind: Secret
metadata:
  name: bot4-secrets
  namespace: production
type: Opaque
data:
  # Database credentials (base64 encoded)
  # echo -n 'your-password' | base64
  db_password: <BASE64_ENCODED_DB_PASSWORD>
  
  # Redis password (base64 encoded)
  redis_password: <BASE64_ENCODED_REDIS_PASSWORD>

---
apiVersion: v1
kind: Secret
metadata:
  name: bot4-exchange-secrets
  namespace: production
type: Opaque
data:
  # Binance API credentials (base64 encoded)
  binance_api_key: <BASE64_ENCODED_BINANCE_API_KEY>
  binance_api_secret: <BASE64_ENCODED_BINANCE_API_SECRET>
  
  # Kraken API credentials (base64 encoded)
  kraken_api_key: <BASE64_ENCODED_KRAKEN_API_KEY>
  kraken_api_secret: <BASE64_ENCODED_KRAKEN_API_SECRET>
  
  # Coinbase API credentials (base64 encoded)
  coinbase_api_key: <BASE64_ENCODED_COINBASE_API_KEY>
  coinbase_api_secret: <BASE64_ENCODED_COINBASE_API_SECRET>

---
# External Secrets Operator configuration (recommended for production)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bot4-vault-secrets
  namespace: production
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: bot4-secrets
    creationPolicy: Owner
  data:
  - secretKey: db_password
    remoteRef:
      key: secret/data/bot4/production/database
      property: password
  - secretKey: redis_password
    remoteRef:
      key: secret/data/bot4/production/redis
      property: password

---
# Vault SecretStore configuration
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: production
spec:
  provider:
    vault:
      server: "https://vault.production.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "bot4-trading"
          serviceAccountRef:
            name: "bot4-trading"