---
# ULTRATHINK ConfigMap
# Team: Full 8-Agent Collaboration
apiVersion: v1
kind: ConfigMap
metadata:
  name: bot4-config
  namespace: bot4-trading
data:
  trading.yaml: |
    # Trading configuration
    system:
      environment: production
      version: 1.0.0
      
    performance:
      decision_latency_us: 100
      tick_processing_us: 10
      order_submission_us: 100
      
    exchanges:
      - name: binance
        enabled: true
        websocket_url: wss://stream.binance.com:9443/ws
        rest_url: https://api.binance.com/api/v3
        rate_limit: 1200
        
      - name: coinbase
        enabled: true
        websocket_url: wss://ws-feed.exchange.coinbase.com
        rest_url: https://api.exchange.coinbase.com
        rate_limit: 10
        
      - name: kraken
        enabled: true
        websocket_url: wss://ws.kraken.com
        rest_url: https://api.kraken.com
        rate_limit: 15
        
      - name: okx
        enabled: true
        websocket_url: wss://ws.okx.com:8443/ws/v5/public
        rest_url: https://www.okx.com/api/v5
        rate_limit: 20
        
      - name: bybit
        enabled: true
        websocket_url: wss://stream.bybit.com/v5/public/spot
        rest_url: https://api.bybit.com
        rate_limit: 50
        
    risk_management:
      max_position_size: 10000
      max_leverage: 3.0
      daily_loss_limit: 5000
      max_drawdown: 0.15
      kelly_fraction: 0.25
      correlation_limit: 0.7
      
    ml_models:
      inference_timeout_ms: 1000
      ensemble_size: 5
      update_interval_hours: 24
      
    circuit_breakers:
      max_consecutive_losses: 5
      toxicity_threshold: 0.8
      latency_threshold_ms: 500
      error_rate_threshold: 0.05
