apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bot4-trading-hpa
  namespace: bot4-trading
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bot4-trading-engine
  minReplicas: 3
  maxReplicas: 10
  metrics:
  # CPU utilization
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  
  # Memory utilization
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  
  # Custom metrics (requires metrics server)
  - type: Pods
    pods:
      metric:
        name: decision_latency_us
      target:
        type: AverageValue
        averageValue: "80"  # Scale up if latency > 80Î¼s
  
  - type: Pods
    pods:
      metric:
        name: orders_per_second
      target:
        type: AverageValue
        averageValue: "10000"  # Scale up if > 10k orders/sec
  
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 120
      selectPolicy: Min
    
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max